### ISSUE TITLE
Scope of 2.2 discussion

### ISSUE THREAD

**Issue by BenRQ** [NPBruce/valkyrie#1012]
The version 2.2 has grown into something big.

Here are _some_ of the most import changes : 
* Scenario explorer v2 (#1007) #832 #938 #957 #958 #961 #962 #963 #1005
* #934 Test variable: add OR condition
* #950 A little brighter tile(s) display area
* #959 Feature: Allow setting a pre-determined solution for a code puzzle.
* #822 Adding conditions to Monster activations
* #609 Tests in starting QItems
* #921 UI Button - Background
* #656 Crawl file system for apps if the registry fails
* #923 Display/modify monster life during monster activation phase
* #821  Spawn Instruction exclusions not working
* #999 Added russian
* #1009  Choice voice acting and image for localization   (Pull request ongoing by @Ssid113 )
* #1000  Enhancement: Localizations' problems enhancement 
* #1047 Unclear text/button when Steam folder is not found enhancement
* #1040 Online Mode/Offline Mode needs translation ScenarioExplorer help wanted

It would probably be good to consider starting testing and releasing this version with the current scope.

But we have some issues planned for 2.2 that are still open, and I'd like to know what all of you (testers, players, developers) would consider as most important for next version.
Of course the complexity of the issue is important, a text change is easier to fit in the version than a big structural change.
Also some bugs are not listed in 2.2, and they may be required. So feel free to point them out in this thread.

Here is the list of issues still open, and planned for 2.2 release.

**These are for the moment still in the scope, or being discussed :**

--

**These are scoped out until someone confirm it is important, or provide help fix it:**
* #823 Improving the usability of random monster groups
* #933 Qitem random 
(I need a scenario test version to reproduce the problem and fix this)
* #901 Monster Spawn needs an overhaul 
* #888 Event-based custom "Investigator Attacks"
* #868 MoM: Integrate Horrific Journeys
(I know you want it @scrubbless ^^ )
* #816 Add #rand entry for booleans  / #271 Var Components
@redwolf2 I think you have started working on this, haven't you ?
* #761 Request to add the $mythosIndoors check to some of the Mythos Events
@nicolazee, this one is up to you :)
* #750 1.7.0b - Investigator variables
This one is not clear for me
* #579 Trigger Event: Defeated Spawn of a Random Group
* #511 Control loaded content in test function
This one has been clarified by @NPBruce and is probably not too urgent

**Comment by redwolf2** [comment]
I think we should skip the var components for 2.3. I am a litte scared of all the breaking changes it might cause at this stage, I merged the latest 2.2 changes in. https://github.com/redwolf2/valkyrie/tree/development_vars
Currenty the saving of the var components is broken. Quest.cs has also become a giant file, that might have to be refactored into several files.

**Comment by DelphiDie** [comment]
Just to give my opinion: #823 is still one of the most imporant additions to the Descent module, since the usability of random monster groups pretty much hinges on this. As long as the thing described in #823 aren't possible, the monster group have to be manually selected which really hurts variability.

**Comment by MrTantum** [comment]
If I understand @DelphiDie correctly (as stated in Discord>Valkyrie app> app-improvements) it would be very usefull for the **Descent Shadow Rune** campaign implementation if you could add #823 to the scope of 2.2. I'm not sure though how complex the implementation of this feature is.

**Comment by Ssid113** [comment]
I do not know whether it is useful, but it seems convenient for me to have a filter on downloaded scenarios.

**Comment by BenRQ** [comment]
@DelphiDie @MrTantum, #821 is still not clear for me. I will ask some questions to try to clarify it and understand how much work we are talking about

**Comment by antontimmermans** [comment]
I think #993 is not a bug but the result of not really understanding how the mechanism works (i had the same problem when I started writing scenarios). It is behaving as described in the manual. But I do have to admit that it is a little confusing that the selection list behaves as an exclusion list in certain conditions. We have the option to:

1. Improve description in the manual -->close this issue and raise one in the tutorial repository: https://github.com/scrubbless/MoM2ndTutorial
2. Change the editor so that it becomes clear when it is an inclusion list or an exclusion list. This would require some thinking on how that would look.

Both options would (for me) result to take it this one out of the 2.2. scope.

**Comment by BenRQ** [comment]
Scope is now closed.

Closing this ticket.
